# Generated by Django 6.0 on 2025-12-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=200)),
                ('bcontent', models.TextField(blank=True, null=True)),
                ('bfile', models.CharField(blank=True, max_length=255, null=True)),
                ('bdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
