# Generated by Django 6.0 on 2025-12-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuscore',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kor', models.IntegerField(default=0)),
                ('eng', models.IntegerField(default=0)),
                ('math', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0)),
            ],
        ),
    ]
