spring.application.name=s0212_02-1

# 인코딩 설정
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# DataSource 및 MyBatis 자동 구성 제외 (DB 설정이 없을 때)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

# jsp 위치 설정 #
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 포트 설정 #
server.port = 8181

# oracle DB 설정 #
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=ora_user
spring.datasource.password=1111

# Mapper.java 파일이 위치한 경로 - Applicaton_config.java
mybatis.type-aliases-package=com.java.dao
# Mapper.xml 파일이 위치한 경로
mybatis.mapper-locations=mapper/**/*.xml
