# Generated by Django 6.0 on 2025-12-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
