# Generated by Django 6.0 on 2026-01-02 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freepost',
            options={'ordering': ['-created_at'], 'verbose_name': '자유게시판', 'verbose_name_plural': '자유게시판'},
        ),
        migrations.AlterField(
            model_name='freepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='category',
            field=models.CharField(choices=[('all', '전체보기'), ('mom', '육아수다'), ('husband', '남편뒷담화'), ('family', '시댁/친정'), ('preg', '임신출산')], default='mom', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
