# Generated by Django 6.0 on 2025-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['sno'], 'verbose_name': '학생', 'verbose_name_plural': '학생들'},
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=100, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(default='익명', max_length=50, verbose_name='닉네임'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=100, verbose_name='비밀번호'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='000-0000-0000', max_length=20, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default='user', max_length=50, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], default='남자', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=models.CharField(default='게임', max_length=100, verbose_name='취미'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
