# Generated by Django 6.0 on 2025-12-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('major', models.CharField(max_length=100, verbose_name='전공')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
