# Generated by Django 6.0 on 2025-12-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='010-0000-0000', max_length=13)),
                ('gender', models.CharField(default='남자', max_length=100)),
                ('hobby', models.CharField(default='게임', max_length=100)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
