# Generated by Django 6.0 on 2025-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_bgroup_board_bstep_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bfile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
