# Generated by Django 6.0 on 2025-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_bfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bindent',
            field=models.IntegerField(default=0),
        ),
    ]
