# Generated by Django 6.0 on 2025-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
